### ISSUE TITLE
Macro not saved

### ISSUE THREAD

**Issue by dnebauer** [kr40/nvim-macros#10]
Problem:

* Installed as per instructions with default options.
* Created macro on `q`
* Ran command `MacroSave q`, entered macro name at prompt, got message saying "Macro NAME saved."
* But no write to actual macro file.

Troubleshooting:

* Created empty `macros.json` in case it needs to exist first -- no effect
* Experimented with macro name formats, e.g., no spaces, all lowercase -- no effect

System:

* linux debian/testing 6.6.13-1 (2024-01-20)
* tmux 3.3a
* alacritty 0.12.2
* NVIM v0.9.5, Build type: Release, LuaJIT 2.1.1692716794

Love the concept of your plugin. Really hope it works for me some day.

**Comment by kr40** [comment]
Can you see it when you do MacroSelect?

**Comment by dnebauer** [comment]
It did, which sent me on a journey of discovery. The `json_file_path` I was setting was a symlink to another file. Turns out this plugin silently trashes the symlink and creates a regular file in its place. I was checking the target file which remained empty and no longer had a symlink pointing to it.

I also noticed errors like `cp: not writing through dangling symlink '/home/david/.local/share/nvim/nvim-macros/backups/20240208222802_macros.json.bak` being written transiently at the cursor location, but disappearing when I moved the cursor!

I'm glad to have solved the problem, but wonder whether `nvim-macros` should respect symlinks set as `json_file_path`. Failing that, perhaps it could signal a warning if the `json_file_path` is a symlink (or anything other than a regular file). Failing that, perhaps a warning on the README page?

Thanks for your help. If you take up my first or second suggestion above I'd be happy to test it.

**Comment by kr40** [comment]
Ok I understand why this is happening, this happens because how I write the json file when we save a new macro. We first write to a tmp file and then save it to the macros file to avoid any errors cropping up during save for another feature I am working on (edit macros). I will try to change it in the next update! Thanks for pointing this out.

**Comment by kr40** [comment]
For some reason I am unable to reproduce it. How are you making symlinks? I made a symlink from my config macros.json to home macros.json and it works as expected. Can you tell me the command you used? Maybe there is a typo in plugin spec that is why it is creating a new file.

**Comment by kr40** [comment]
Can you check now? Before doing that, just delete backup folder which is in `home/david/.local/share/nvim/nvim-macros` and make sure that the symlink file exists before saving and make sure not typos in `json_file_path`. This should now work properly with saving and backups should work aswell.

**Comment by dnebauer** [comment]
It's working perfectly with symlinks now. I've tried the default `json_file_path` and a custom location. I've also confirmed the backup files are saving correctly. This plugin is going to save me a _lot_ of time. Thanks for your effort in creating it.
